name: ManifestSpawn
version: '0.0.2-1.20.1'
main: com.bshaven.manifestspawn.ManifestSpawn
api-version: '1.20'
commands:
  spawn:
  setspawn:
  msreload:
permissions:
  manifestspawn.setspawn:   # Add this line for the /setspawn permission
    description: Allows players to set the custom spawn location.
    default: op
  manifestspawn.msreload: # Add this line for the /msreload permission
    description: Allows players to reload the plugin configuration.
    default: op